export default [
  { name: "Afrikaans", id: "af" },
  { name: "Albanian", id: "sq" },
  { name: "Amharic", id: "am" },
  { name: "Arabic", id: "ar" },
  { name: "Armenian", id: "hy" },
  { name: "Assamese*", id: "as" },
  { name: "Aymara*", id: "ay" },
  { name: "Azerbaijani", id: "az" },
  { name: "Bambara*", id: "bm" },
  { name: "Basque", id: "eu" },
  { name: "Belarusian", id: "be" },
  { name: "Bengali", id: "bn" },
  { name: "Bhojpuri*", id: "bho" },
  { name: "Bosnian", id: "bs" },
  { name: "Bulgarian", id: "bg" },
  { name: "Catalan", id: "ca" },
  { name: "Cebuano", id: "ceb" },
  { name: "Chinese (Simplified)", id: "zh-CN or zh (BCP-47)" },
  { name: "Chinese (Traditional)", id: "zh-TW (BCP-47)" },
  { name: "Corsican", id: "co" },
  { name: "Croatian", id: "hr" },
  { name: "Czech", id: "cs" },
  { name: "Danish", id: "da" },
  { name: "Dhivehi*", id: "dv" },
  { name: "Dogri*", id: "doi" },
  { name: "Dutch", id: "nl" },
  { name: "English", id: "en" },
  { name: "Esperanto", id: "eo" },
  { name: "Estonian", id: "et" },
  { name: "Ewe*", id: "ee" },
  { name: "Filipino (Tagalog)", id: "fil" },
  { name: "Finnish", id: "fi" },
  { name: "French", id: "fr" },
  { name: "Frisian", id: "fy" },
  { name: "Galician", id: "gl" },
  { name: "Georgian", id: "ka" },
  { name: "German", id: "de" },
  { name: "Greek", id: "el" },
  { name: "Guarani*", id: "gn" },
  { name: "Gujarati", id: "gu" },
  { name: "Haitian Creole", id: "ht" },
  { name: "Hausa", id: "ha" },
  { name: "Hawaiian", id: "haw" },
  { name: "Hebrew", id: "he or iw" },
  { name: "Hindi", id: "hi" },
  { name: "Hmong", id: "hmn" },
  { name: "Hungarian", id: "hu" },
  { name: "Icelandic", id: "is" },
  { name: "Igbo", id: "ig" },
  { name: "Ilocano*", id: "ilo" },
  { name: "Indonesian", id: "id" },
  { name: "Irish", id: "ga" },
  { name: "Italian", id: "it" },
  { name: "Japanese", id: "ja" },
  { name: "Javanese", id: "jv or jw" },
  { name: "Kannada", id: "kn" },
  { name: "Kazakh", id: "kk" },
  { name: "Khmer", id: "km" },
  { name: "Kinyarwanda", id: "rw" },
  { name: "Konkani*", id: "gom" },
  { name: "Korean", id: "ko" },
  { name: "Krio*", id: "kri" },
  { name: "Kurdish", id: "ku" },
  { name: "Kurdish (Sorani)*", id: "ckb" },
  { name: "Kyrgyz", id: "ky" },
  { name: "Lao", id: "lo" },
  { name: "Latin", id: "la" },
  { name: "Latvian", id: "lv" },
  { name: "Lingala*", id: "ln" },
  { name: "Lithuanian", id: "lt" },
  { name: "Luganda*", id: "lg" },
  { name: "Luxembourgish", id: "lb" },
  { name: "Macedonian", id: "mk" },
  { name: "Maithili*", id: "mai" },
  { name: "Malagasy", id: "mg" },
  { name: "Malay", id: "ms" },
  { name: "Malayalam", id: "ml" },
  { name: "Maltese", id: "mt" },
  { name: "Maori", id: "mi" },
  { name: "Marathi", id: "mr" },
  { name: "Meiteilon (Manipuri)*", id: "mni-Mtei" },
  { name: "Mizo*", id: "lus" },
  { name: "Mongolian", id: "mn" },
  { name: "Myanmar (Burmese)", id: "my" },
  { name: "Nepali", id: "ne" },
  { name: "Norwegian", id: "no" },
  { name: "Nyanja (Chichewa)", id: "ny" },
  { name: "Odia (Oriya)", id: "or" },
  { name: "Oromo*", id: "om" },
  { name: "Pashto", id: "ps" },
  { name: "Persian", id: "fa" },
  { name: "Polish", id: "pl" },
  { name: "Portuguese", id: "pt" },
  { name: "Punjabi", id: "pa" },
  { name: "Quechua*", id: "qu" },
  { name: "Romanian", id: "ro" },
  { name: "Russian", id: "ru" },
  { name: "Samoan", id: "sm" },
  { name: "Sanskrit*", id: "sa" },
  { name: "Scots Gaelic", id: "gd" },
  { name: "Sepedi*", id: "nso" },
  { name: "Serbian", id: "sr" },
  { name: "Sesotho", id: "st" },
  { name: "Shona", id: "sn" },
  { name: "Sindhi", id: "sd" },
  { name: "Sinhala (Sinhalese)", id: "si" },
  { name: "Slovak", id: "sk" },
  { name: "Slovenian", id: "sl" },
  { name: "Somali", id: "so" },
  { name: "Spanish", id: "es" },
  { name: "Sundanese", id: "su" },
  { name: "Swahili", id: "sw" },
  { name: "Swedish", id: "sv" },
  { name: "Tagalog (Filipino)", id: "tl" },
  { name: "Tajik", id: "tg" },
  { name: "Tamil", id: "ta" },
  { name: "Tatar", id: "tt" },
  { name: "Telugu", id: "te" },
  { name: "Thai", id: "th" },
  { name: "Tigrinya*", id: "ti" },
  { name: "Tsonga*", id: "ts" },
  { name: "Turkish", id: "tr" },
  { name: "Turkmen", id: "tk" },
  { name: "Twi (Akan)*", id: "ak" },
  { name: "Ukrainian", id: "uk" },
  { name: "Urdu", id: "ur" },
  { name: "Uyghur", id: "ug" },
  { name: "Uzbek", id: "uz" },
  { name: "Vietnamese", id: "vi" },
  { name: "Welsh", id: "cy" },
  { name: "Xhosa", id: "xh" },
  { name: "Yiddish", id: "yi" },
  { name: "Yoruba", id: "yo" },
  { name: "Zulu", id: "z" },
];
